spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: micro-service-config-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/phonemarket2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  redis:
    host: 127.0.0.1

mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  type-aliases-package: com.cy.joy.pojo
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: micro-service-config-provider
    prefer-ip-address: true

info:
  app.name: cy-micro-service
  company.name: www.cy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: micro-service-config-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/phonemarket2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  redis:
    host: 127.0.0.1

mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  type-aliases-package: com.cy.joy.pojo
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: micro-service-config-provider
    prefer-ip-address: true

info:
  app.name: cy-micro-service
  company.name: www.cy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
